# Generated by Django 4.2.4 on 2023-08-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('vnc_url', models.URLField()),
                ('rdpc_url', models.URLField()),
                ('rdps_url', models.URLField()),
            ],
        ),
    ]
